#set server port
server:
  port: 8084
#set application name
spring:
  application:
    name: API-GATEWAY


#congigure cloud gateway to All api pass this url
  cloud:
    gateway:
      routes:
    #for user service
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
    #for hotel service
        - id: HOTEL-SERVICE
          uri: lb://HOTEL-SERVICE
          predicates:
            - Path=/hotels/**
    #for rating service
        - id: RATING-SERVICE
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/ratings/**





#Eureka server configuration
eureka:
    instance:
      prefer-ip-address: true
    client:
      fetch-registry: true
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka
        #      defaultZone: http ://localhost:8761/eureka