server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratingservice_db
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  #spring.datasource.driver-class-name=com.mysql.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
  application:
    name: RATING-SERVICE
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


